### ISSUE TITLE
Add Rubocop to CircleCI

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#11]
This seems a simple solution:
https://gist.github.com/djburdick/5104d15f612c15dde65f

It adds a spec that runs Rubocop, so no extra configuration is needed.

In order to use that, we should check Rubocop configuration to see which rules/files to ignore, it seems not all of them will make sense to the project.

For example:
- Should rails_helper and spec_helper be checked? There are offenses that were generated automatically by Rails.

- "Line is too long" for the Gemfile
Gemfile:38:85: C: Line is too long. [102/80]
  gem 'shoulda-matchers', git: 'https://github.com/thoughtbot/shoulda-matchers.git', branch: 'rails-5'
                                                                                    ^^^^^^^^^^^^^^^^^^

- Ok, this can be refactored
spec/requests/series/show_spec.rb:5:1: C: Block has too many lines. [39/25]
RSpec.describe 'Show series', type: :request do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

- I'm still studying how :dependent works
app/models/section.rb:8:3: C: Specify a :dependent option.
  has_many :subsections
  ^^^^^^^^

- Changing the syntax didn't work when I tried, but I haven't read the gem docs yet.
app/models/subscription.rb:17:18: C: Use the new Ruby 1.9 hash syntax.
      transition :pending => :rejected
                 ^^^^^^^^^^^

**Comment by danielweinmann** [comment]
@felipefreitag, I think the "add spec" solution is not good. Did you try adding something like the following to `.circleci/config.yml`?

```
      # run tests!
      - run:
          name: run rubocop
          command: bin/rubocop
```

PS: I think it is better to add Rubocop `before` RSpec, since with time the specs tend to be heavier than linting. That way the CI doesn't even bother to run the specs if there are Rubocop offenses.
