### ISSUE TITLE
Eslint check on default Rails cable.js file

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#26]
Codeclimate > eslint was bringing up this issue:

```
Expected an assignment or function call and instead saw an expression. NEW

  this.App || (this.App = {});
Severity: MinorFound in app/assets/javascripts/cable.js by eslint
```

I excluded this file from the verification since this syntax seems to have a particular purpose.

**Comment by danielweinmann** [comment]
Instead of excluding de the check, please exclude `cable.js` and `channels` folder from javascripts assets folder.

We already excluded the other references to action cable from the project ;) if we decide we need it in the future (not likely, I guess), then we add it back.
