### ISSUE TITLE
Add sass-lint to our CI stack

### ISSUE THREAD

**Issue by danielweinmann** [felipefreitag/pangeas#38]
https://github.com/sasstools/sass-lint

**Comment by felipefreitag** [comment]
@danielweinmann , I'll add sass-lint, but if this is about the long lines in the gradient descriptions:
https://github.com/sass/sass/issues/216
I've found it's not possible to break lines with sass, only with scss. Do you have another way?

**Comment by danielweinmann** [comment]
No worries :D if I had noticed the long lines I'd have commented on your PRs :P

I just thought that the sass files are the only part of the software that is not covered by linting ;)

**Comment by felipefreitag** [comment]
Ok! FYI: CodeClimate supports scss-lint, I didn't add it to the project because there are rules that are different from sass-lint (like hex colors needing to be all lowercase / all caps).

**Comment by danielweinmann** [comment]
Thanks, good to know. Let's see which one we prefer over time :)
