### ISSUE TITLE
Show user page

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#41]
The design has a 'my profile' page.
![5 - tela meu perfil_pangeas_logado_22-08-17](https://user-images.githubusercontent.com/6249611/31729777-c00e379e-b40e-11e7-885a-16a4d75a8d11.jpg)

Devise only offers a user/edit page
![user-edit](https://user-images.githubusercontent.com/6249611/31729779-c58f4762-b40e-11e7-80aa-0ac6102785f0.png)

I searched for solutions and there's a suggestion to create a `users` controller with a `show` action. Is that the desired path? We'd have to scope the user by hand to prevent reaching other people's profiles.

I also thought of the option of adding parts o the design to user#edit, thus using Devise's standard route.

What do you think @danielweinmann ?

**Comment by danielweinmann** [comment]
I think we should try to launch with the devise form only, not following the design for this page :) at least we should release like that for them and see what they think :)
