### ISSUE TITLE
Creating and testing the webhook

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#54]
Test webhook on Heroku

**Comment by felipefreitag** [comment]
The webhook is making the right request and the processing seems to be working, but there isn't any authentication and Rails is complaining:

![heroku-request](https://user-images.githubusercontent.com/6249611/32549444-9f40f26e-c470-11e7-8104-3e9df36a53b9.png)

@danielweinmann , I've found a few possible workarounds online (like skipping the CSRF authentication) but I'd like to talk and understand this better before jumping to solutions.

**Comment by danielweinmann** [comment]
`skip_before_action :verify_authenticity_token, only: %i[activate]`
