### ISSUE TITLE
Owl carousel stylesheet not found in production

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#59]
It should be looking for it at `node_modules/` but it's trying `assets/` , even though the `node_modules` path is included at Rails config: `config/initializers/assets.rb`
`Rails.application.config.assets.paths << Rails.root.join('node_modules')`

![screenshot from 2017-11-08 10-48-21](https://user-images.githubusercontent.com/6249611/32549932-5dd2d4f8-c472-11e7-8e5c-96eacb91e817.png)

**Comment by danielweinmann** [comment]
Man, I think we could make this work, but I don't see much advantage in spending time tweaking that.

Let's use a hosted version of OwlCarousel like this instead: https://cdnjs.com/libraries/OwlCarousel2
