### ISSUE TITLE
JS not loading when navigating through links

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#6]
JS isn't loaded when a page is rendered through an internal link.
For example: From root, click 'Vida em Equilíbrio' section. The carousel and smooth scroll won't be working.
It starts working with a hard refresh.
It seems a known issue with JQuery and Turbolinks: https://stackoverflow.com/questions/37797741/rails-5-turbolinks-5-some-js-not-loaded-on-page-render

**Comment by danielweinmann** [comment]
This is what you should do: https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads

Here you can find an example: https://github.com/danielweinmann/tangueros/blob/master/app/assets/javascripts/application.js#L22
